name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build binaries
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          COMMIT=${GITHUB_SHA::8}
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          LDFLAGS="-s -w -X main.Version=${VERSION} -X main.GitCommit=${COMMIT} -X main.BuildDate=${BUILD_DATE}"

          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o dist/s3-mcp-server-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o dist/s3-mcp-server-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o dist/s3-mcp-server-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o dist/s3-mcp-server-darwin-arm64 .
          GOOS=windows GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o dist/s3-mcp-server-windows-amd64.exe .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
